{"name": "test_success_get_task", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('get_list_id', <SubRequest 'create_and_delete_task' for <Function test_success_get_task>>)", "trace": "file c:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\api\\test_tasks.py, line 41\n      @allure.description(\"Проверка получения списка задач\")\n      def test_success_get_task(self, tasks_client, create_and_delete_task, get_list_id):\nfile c:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\conftest.py, line 28\n  @pytest.fixture\n  def create_and_delete_task(get_list_id):\nE       fixture 'get_list_id' not found\n>       available fixtures: _verify_url, auth_session, authorized_user, base_url, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, clickup_ids, create_and_delete_task, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, sync_browser, tasks_client, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nc:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\conftest.py:28"}, "description": "Проверка получения списка задач", "start": 1744799742476, "stop": 1744799742476, "uuid": "ce4e1db3-0009-42af-8716-0c3710ab7e93", "historyId": "884fa63f1090817b2251fa5e5cd5bd60", "testCaseId": "884fa63f1090817b2251fa5e5cd5bd60", "fullName": "tests.api.test_tasks.TestTasks#test_success_get_task", "labels": [{"name": "feature", "value": "API: Работа с задачами"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "25968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}