{"name": "test_fail_update_task", "status": "passed", "description": "Проверка ошибки при обновлении задачи с некорректным статусом", "steps": [{"name": "Обновляем заголовки на POST", "status": "passed", "start": 1744822004736, "stop": 1744822004736}, {"name": "Отправляем PUT-запрос с несуществующим статусом", "status": "passed", "start": 1744822004736, "stop": 1744822005056}, {"name": "Проверяем ошибку в теле ответа", "status": "passed", "start": 1744822005056, "stop": 1744822005056}], "start": 1744822004736, "stop": 1744822005057, "uuid": "3e1d0b44-bb1f-4ae3-a3a1-1ee8c06bd282", "historyId": "93a51c71bf9f1aaacb1b43954b741361", "testCaseId": "93a51c71bf9f1aaacb1b43954b741361", "fullName": "tests.api.test_tasks.TestTasks#test_fail_update_task", "labels": [{"name": "feature", "value": "API: Работа с задачами"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "2872-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}