{"name": "test_success_create_task", "status": "failed", "statusDetails": {"message": "Failed: ScopeMismatch: You tried to access the function scoped fixture tasks_client with a session scoped request object. Requesting fixture stack:\ntests\\conftest.py:43:  def get_list_id(tasks_client)\nRequested fixture:\ntests\\conftest.py:22:  def tasks_client()", "trace": "ScopeMismatch: You tried to access the function scoped fixture tasks_client with a session scoped request object. Requesting fixture stack:\ntests\\conftest.py:43:  def get_list_id(tasks_client)\nRequested fixture:\ntests\\conftest.py:22:  def tasks_client()"}, "description": "Проверка успешного создания задачи", "start": 1744799822011, "stop": 1744799822011, "uuid": "9d8c77d1-2f0b-4c12-bc32-a5d689693994", "historyId": "4fefddb7f118c63b054dd34a1f7caadb", "testCaseId": "4fefddb7f118c63b054dd34a1f7caadb", "fullName": "tests.api.test_tasks.TestTasks#test_success_create_task", "labels": [{"name": "feature", "value": "API: Работа с задачами"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "8224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}