{"name": "test_fail_delete_task", "status": "failed", "statusDetails": {"message": "Failed: ScopeMismatch: You tried to access the function scoped fixture tasks_client with a session scoped request object. Requesting fixture stack:\ntests\\conftest.py:43:  def get_list_id(tasks_client)\nRequested fixture:\ntests\\conftest.py:22:  def tasks_client()", "trace": "ScopeMismatch: You tried to access the function scoped fixture tasks_client with a session scoped request object. Requesting fixture stack:\ntests\\conftest.py:43:  def get_list_id(tasks_client)\nRequested fixture:\ntests\\conftest.py:22:  def tasks_client()"}, "description": "Проверка ошибки при удалении задачи с некорректными заголовками", "start": 1744799822043, "stop": 1744799822043, "uuid": "314db28d-1968-4379-980f-aa09635ccea1", "historyId": "fca0feda91469001c721842c2aa8b58f", "testCaseId": "fca0feda91469001c721842c2aa8b58f", "fullName": "tests.api.test_tasks.TestTasks#test_fail_delete_task", "labels": [{"name": "feature", "value": "API: Работа с задачами"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "8224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}