{"name": "test_fail_delete_task", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('get_list_id', <SubRequest 'create_and_delete_task' for <Function test_fail_delete_task>>)", "trace": "file c:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\api\\test_tasks.py, line 108\n      @allure.description(\"Проверка ошибки при удалении задачи с некорректными заголовками\")\n      def test_fail_delete_task(self, tasks_client, create_and_delete_task, get_list_id):\nfile c:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\conftest.py, line 28\n  @pytest.fixture\n  def create_and_delete_task(get_list_id):\nE       fixture 'get_list_id' not found\n>       available fixtures: _verify_url, auth_session, authorized_user, base_url, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, clickup_ids, create_and_delete_task, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, sync_browser, tasks_client, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nc:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\conftest.py:28"}, "description": "Проверка ошибки при удалении задачи с некорректными заголовками", "start": 1744799742485, "stop": 1744799742485, "uuid": "cb068cfd-6cd0-4a8e-9c04-8c1953269c25", "historyId": "fca0feda91469001c721842c2aa8b58f", "testCaseId": "fca0feda91469001c721842c2aa8b58f", "fullName": "tests.api.test_tasks.TestTasks#test_fail_delete_task", "labels": [{"name": "feature", "value": "API: Работа с задачами"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "25968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}