{"name": "test_fail_update_task", "status": "passed", "description": "Проверка ошибки при обновлении задачи с некорректным статусом", "steps": [{"name": "Обновляем заголовки на POST", "status": "passed", "start": 1744800209974, "stop": 1744800209974}, {"name": "Отправляем PUT-запрос с несуществующим статусом", "status": "passed", "start": 1744800209974, "stop": 1744800210298}, {"name": "Проверяем ошибку в теле ответа", "status": "passed", "start": 1744800210298, "stop": 1744800210298}], "start": 1744800209974, "stop": 1744800210298, "uuid": "50a0b467-19a2-4e9a-97b9-48c0ac26d6d2", "historyId": "93a51c71bf9f1aaacb1b43954b741361", "testCaseId": "93a51c71bf9f1aaacb1b43954b741361", "fullName": "tests.api.test_tasks.TestTasks#test_fail_update_task", "labels": [{"name": "feature", "value": "API: Работа с задачами"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "16732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}