{"name": "test_fail_update_task", "status": "passed", "description": "Проверка ошибки при обновлении задачи с некорректным статусом", "steps": [{"name": "Обновляем заголовки на POST", "status": "passed", "start": 1744798872557, "stop": 1744798872557}, {"name": "Отправляем PUT-запрос с несуществующим статусом", "status": "passed", "start": 1744798872557, "stop": 1744798872849}, {"name": "Проверяем ошибку в теле ответа", "status": "passed", "start": 1744798872849, "stop": 1744798872849}], "start": 1744798872557, "stop": 1744798872849, "uuid": "997797c6-2a3b-4452-8251-c0f939e3fd87", "historyId": "93a51c71bf9f1aaacb1b43954b741361", "testCaseId": "93a51c71bf9f1aaacb1b43954b741361", "fullName": "tests.api.test_tasks.TestTasks#test_fail_update_task", "labels": [{"name": "feature", "value": "API: Работа с задачами"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "2352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}