{"name": "test_fail_login", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TargetClosedError: Page.goto: Target page, context or browser has been closed\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"", "trace": "self = <clickup_tests.tests.ui.test_login_page.TestLogin object at 0x00000184A920BAD0>\nsync_browser = <Browser type=<BrowserType name=chromium executable_path=C:\\Users\\Sanchez\\AppData\\Local\\ms-playwright\\chromium-1161\\chrome-win\\chrome.exe> version=134.0.6998.35>\n\n    @allure.description(\"Проверка ошибки при некорректном пароле\")\n    def test_fail_login(self, sync_browser):\n        with allure.step(\"Создаём новую страницу браузера\"):\n            page = sync_browser.new_page()\n    \n        with allure.step(\"Выполняем логин с некорректным паролем\"):\n            login_page = LoginPage(page)\n>           login_page.bad_login(CLICKUP_EMAIL, \"12345678\")\n\ntests\\ui\\test_login_page.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages\\login_page.py:22: in bad_login\n    self.navigate_to()\npages\\base_page.py:18: in navigate_to\n    self.page.goto(full_url)\n.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:9020: in goto\n    self._sync(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py:552: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py:145: in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <playwright._impl._connection.Connection object at 0x00000184A9208200>, cb = <function Channel.send.<locals>.<lambda> at 0x00000184A94B3060>, is_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TargetClosedError: Page.goto: Target page, context or browser has been closed\nE           Call log:\nE             - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:528: TargetClosedError"}, "description": "Проверка ошибки при некорректном пароле", "steps": [{"name": "Создаём новую страницу браузера", "status": "passed", "start": 1744799825720, "stop": 1744799825801}, {"name": "Выполняем логин с некорректным паролем", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TargetClosedError: Page.goto: Target page, context or browser has been closed\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"c:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\ui\\test_login_page.py\", line 25, in test_fail_login\n    login_page.bad_login(CLICKUP_EMAIL, \"12345678\")\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\pages\\login_page.py\", line 22, in bad_login\n    self.navigate_to()\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\pages\\base_page.py\", line 18, in navigate_to\n    self.page.goto(full_url)\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9020, in goto\n    self._sync(\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1744799825801, "stop": 1744799827844}], "start": 1744799825720, "stop": 1744799827846, "uuid": "c9f8f74d-8162-438b-ae10-c6bae0f94e4c", "historyId": "4f543d8847a5db1fd4946b1c5ad7c73b", "testCaseId": "4f543d8847a5db1fd4946b1c5ad7c73b", "fullName": "tests.ui.test_login_page.TestLogin#test_fail_login", "labels": [{"name": "feature", "value": "UI: Авторизация"}, {"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_login_page"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "8224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_login_page"}]}